# Limitations
*I.e., the things I know that I do not yet know*

## Other methods
As mentioned, this is one particular way of doing things. You may also wish to check out R packages people have created for their theses

- [thesisdown](https://github.com/ismayc/thesisdown): Thesis template designed for Reed College.
  - [Gitbook output](https://thesisdown.netlify.com/)
  - [PDF output](https://github.com/ismayc/thesisdown_book/blob/gh-pages/thesis.pdf)
- Many others have developed customized versions of this for their universities. See the `thesisdown` site for a list of other available templates.
- Perhaps the Western templates could eventually be incorporated in this

## Woe is Word...

Many of the issues I run into have to do with strange behaviour in Microsoft Word. For example:

### Table formatting

Table formatting is ugly with `kable()`. There are alternatives to `kable` that are specifically designed for .docx output. These are lovely alternatives to use if you are only outputting to Word (or HTML), but I have repeatedly run into problems with these other options playing nice when alternating between .pdf and .docx outputs.

Table formatting packages for .docx outputs:

- [flextable](https://cran.r-project.org/web/packages/flextable/vignettes/overview.html)
- [captioner](https://cran.r-project.org/web/packages/captioner/vignettes/using_captioner.html)
- [kableExtra::as_image()](https://haozhu233.github.io/kableExtra/save_kable_and_as_image.html)

### Parameter files: A neater, nicer way?

In its current format, all your writing is in RMarkdown except when it comes to your pre-body text, which have to be done in the `doc_preface.tex`. This is not a huge concern, though eventually down the line it would be nice to somehow incorporate this text into RMarkdown documents as well for total continuity. Alas, today is not that day.

Additionally, providing more than style specifications to Word documents is a tricky business, and one I do not have a firm grasp on. At the moment, the .docx template provided tells RMarkdown/bookdown how to *style* the document, but does **not** include the abstract.

My rationalization for not worrying about this is that the .docx versions, for me, are intermediary; they are not the final product, and so fussing about the fine grained details is not a good use of time. However, it may be the case that someone down the line would prefer to use a .docx output every step of the way, right up until the final submission. In this case, more tweaking would need to be done.

I have many more complaints about outputting to word (see Table gripes up above), but I think these limitations are not related to the fact that solutions don't exist, but that I haven't figured them out yet and have decided to stop worrying.